micronaut:
  application:
    name: micronautSession
  security:
    authentication: session
    redirect:
      login-success: /
      login-failure: /login/authFailed
    # endpoints:
      # login:
        # enabled: true
        # path: /login/auth
datasource:
  driver-class-name: com.mysql.jdbc.Driver
  # url: jdbc:mysql://localhost:3306/{DB_NAME}
  # username: {USER_NAME}
  # password: {PASSWORD}
  url: jdbc:mysql://localhost:3306/testdb
  username: test
  password: test
  port: 3307
  # dialect: MySqlDialect
