micronaut:
  application:
    name: micronautSession
  security:
    authentication: session
    redirect:
      login-success: /
      login-failure: /login/authFailed
    # endpoints:
      # login:
        # enabled: true
        # path: /login/auth
